#import "@preview/rubber-article:0.4.1": *
#import "@preview/ctheorems:1.1.3": *

//basic template setup
#show: article.with(
  header-display: true,
  eq-numbering: "(1.1)",
  eq-chapterwise: true,
  margins: 1.0in,
)
#show: thmrules

//math environment setup
#let myQuestion = thmbox(
  "theorem", "Question",
  fill: rgb(232,232,248),
  stroke: rgb(46,46,50)
)
#let myThm = thmbox(
  "theorem", "Theorem",
  fill: rgb(22, 106, 250, 40),
  stroke: rgb(5, 27, 62)
)
#let myDef = thmbox(
  "theorem", "Definition",
  fill: rgb(0,200,220, 20),
  stroke: rgb(0,43,43)
)
#let myProp = thmbox(
  "theorm", "Proposition",
  fill: rgb(50,250,50, 20),
  stroke: rgb(10,50,10) 
)
#let myLemma = thmbox(
  "theorem", "Lemma",
  fill: rgb(96,250, 153, 30),
  stroke: rgb(20,50,35)
)

//common syntaxes needed
#let neq = $!=$
//analysis 
#let Vol = $"Vol"$
//algebra
#let Hom = $"Hom"$
#let End = $"End"$
#let Aut = $"Aut"$
#let Coker = $"Coker"$
#let Gal = $"Gal"$
#let Nil = $"Nil"$
#let char = $"char"$
//complex 
#let Real = $"Re"$
#let Imag = $"Im"$ //also used for image
#let Arg = $"Arg"$
#let Res = $"Res"$
//lie algebra
#let gl = $frak("gl")$
#let sl = $frak("sl")$
#let sp = $frak("sp")$


//start document
#maketitle(
  title: "Commutative Algebra Chapter 7",
  authors: ("Zih-Yu Hsieh",),
  date: datetime.today().display("[month repr:long] [day], [year]"),
)

= ND //1
#myQuestion[
  Let $A$ be a non-Noetherian ring and let $Sigma$ be the set of ideals in $A$ which are not finitely generated. Show that $Sigma$ has maximal elements and that the maximal elements of $Sigma$ are prime ideals.
]
#text(weight: "bold")[Pf:]

Since $A$ is assumed to be non-Noetherian, $Sigma$ is nonempty. $Sigma$ together with inclusion forms a POset, to prove that it has maximal elements, consider any chain $C subset.eq Sigma$: 

Let $I_C := union.big_(I in C)I$ (union of ideals, which forms an ideal also), we claim that $I_C$ is not finitely generated. Suppose the contrary that it's finitely generated, then there exists $x_1,...,x_n in I_C$ such that $I_C=(x_1,...,x_n)$. For each index $i=1,...,n$ there exists a corresponding ideal $I_(a_i) in C$ with $x_i in I_(a_i)$, and by the fact that $C$ is a chain (which has a total order), one can order them in a way such that all $I_(a_i) subset.eq I_(a_n)$, hence all $x_i in I_(a_i) subset.eq I_(a_n)$, showing that $(x_1,...,x_n) = I_C subset.eq I_(a_n)$, while $I_(a_n) subset.eq I_C$ by definition of how $I_C$ is constructed. Hence, $I_(a_n)=I_C$, which $I_(a_n) in C subset.eq Sigma$ is finitely generated.

Yet, this contradicted the fact that $Sigma$ only collects the non-finitely generated ideals. Hence, our assumption is false, $I_C$ must not be finitely generated, hence $I_C in Sigma$ serves as an upper bound for the chain $C$. Since all chain has an upper bound, by Zorn's Lemma $Sigma$ in fact has maximal elements.

\ 

Now, to prove that the maximal elements  $P in Sigma$ are prime ideals, suppose the contrary that it is not prime. Then, there exists $x,y in A\\P$ such that $x y in P$...

= D //2
#myQuestion[
  Let $A$ be a Noetherian ring and let $f=sum_(n=0)^infinity a_n x^n in A[[x]]$. Prove that $f$ is nilpotent if and only if each $a_n$ is nilpotent.
]
#text(weight: "bold")[Pf:]

$==>:$ First suppose $f$ is nilpotent, then there exists $n in NN$ such that $f^n=0$.

First, for $k=0$, since $f^n=0$ has the zeroth degree coefficient being $a_0^n$, then $a_0^n=0$, showing that $a_0 in A$ is nilpotent (which is also nilpotent within $A[[x]]$). Hence, with $A[[x]]$ being commutative (i.e. nilradical is an ideal), we have $f^n - a_0 = sum_(i=1)^infinity a_i x^i$ being nilpotent also.

Inductively, assume that for given $k in NN$, $a_0,...,a_k$ are all nilpotent (hence the corresponding $a_i x^i$ for $i=0,...,k$ are all nilpotent in $A[[x]]$ also). Then, this implies that $g=sum_(i=k+1)^infinity a_i x^i = f - sum_(i=0)^k a_i x^i$ is also nilpotent. Hence, with $g^m = 0$ for some $m in NN$, since $g^m$ has $(k+1)m$ degree's coefficient being $a_(k+1)^m$ (all previous terms are $0$, so have no effect), then $a_(k+1)^m=0$, showing $a_(k+1)$ is also nilpotent.

Hence, by induction one can say that $f$ is nilpotent implies all its coefficients are nilpotent.

\ 

$<==:$ Suppose that each $a_n$ is nilpotent. Consider the ideal $I subset.eq A$ generated by all $a_n$ (where $n in NN$). Notice that all $a_n in Nil(A)$, hence $I subset.eq Nil(A)$. With $Nil(A)$ being nilpotent for Noetherian Ring (a theorem listed in Chapter 7), then we have $I^n subset.eq (Nil(A))^n = (0)$ for some $n in NN$. Then, in this case if consider $f^n$, all of its coefficients would be finite sum of products of $n$ $a_i$s multiplied together (not necessarily distinct), which all the coefficients belong to $I^n = (0)$, hence $f^n=0$.

(Pf: For $n=1$, we have all the coefficients $a_i in I^1=I$; suppose for given $k in NN$ we have $f^k=sum_(i=0)^infinity b_i x^i$ with all coefficients $b_i in I^k$, then:
$ f^(k+1) = (sum_(i=0)^infinity b_i x^i)(sum_(j=0)^infinity a_j x^j) = sum_(l=0)^infinity (sum_(i=0)^l b_i a_(l-i))x^l $
Where each $sum_(i=0)^l b_i a_(l-i) in I^(k+1)$, since $b_i in I^k$ and $a_(l-i) in I$, so by induction $f^k$ has all its coefficients in $I^k$ for all $k in NN$).

= ND //3
#myQuestion[
  Let $I$ be an irreducible ideal in a ring $A$. Then TFAE:
  1. $I$ is primary
  2. For every multiplicatively closed subset $S$ of $A$ we have $(S^(-1)I)^c = (I:x)$ for some $x in S$
  3. The sequence $(I:x^n)$ is stationary for all $x in A$.
]
#text(weight: "bold")[Pf:]

$1==>2:$ suppose $I$ is primary, then by theorems 

= ND //4
#myQuestion[
  Which of the following rings (of complex holomorphic functions) are Noetherian?
  1. The ring of rational functions of $z$ with no pole on the circle $|z|=1$.
  2. The ring of power series in $z$ with a positive radius of convergence (centered at $z=0$).
  3. The ring of power series in $z$ with an infinite radius of convergence.
  4. The ring of polynomials in $z$ whose first $k$ derivatives vanish at the origin ($k in NN$ is fixed)
  5. The ring of polynomials in $z,w$ all of whose partial derivatives with respect to $w$ vanish for $z=0$.
]
#text(weight: "bold")[Pf:]

1. To prove that it's not Noetherian, consider $I_n$ being the ideal such that all $p^n$ related roots of unity are all zeros of the functions in $I_n$

2. To show that it is not finitely generated, consider the collection of ideals $I_n subset.eq CC[[z]]$, such that $I_n$ only contains power series with radius of convergence $r<=n$. Then, based on construction we automatically has $I_1 subset.eq I_2 subset.eq ... subset.eq I_n subset.eq ...$, which forms an ascending chain.

  On the other hand, this is also a strict ascending chain: Given a power series $sum_(k=0)^infinity a_k z^k$, its radius of convergence is $R=(lim sup root(k, a_k))^(-1)$. Then, take each $a_k = (1/n)^k dot k$, then we have $lim sup root(k, a_k) = lim_(k arrow.r infinity)root(k, (1/n)^k dot k) = lim_(k arrow.r infinity)1/n dot root(k,k) = 1/n$, which the corresponding radius of convergence is $R = (lim sup root(k,a_k))^(-1) = 1/(1/n) = n$.

  Hence, each $I_n$ is directly containing a power series with $n$ as the radius of convergence, showing that the chain of ideals must be strictly increasing. This shows that the given ring is not satisfying ascending chain condition, hence not Noetherian.

3. This ring from complex analytic point of view, is all the complex function analytic over the whole complex field $CC$ (since each power series with infinite radius of convergence is analytic over the whole $CC$, while a function analytic over $CC$ has a power series expansion of infinite radius of convergence), hence we're working over $cal(O)(CC)$ (ring of all function analytic over $CC$).

  This ring unfortunately is not Noetherian (not all ideals are finitely generated): Consider the ideal $I subset cal(O)(CC)$, that contains all analytic functions with zeros on all $m ZZ$ for some fixed nonzero $m in ZZ$. This ideal is not finitely generate: Suppose the contrary that it is, there exists $f_1,...,f_n in I$, such that $I=(f_1,...,f_n)$. These $f_i$ each has $m_i in ZZ$ such that $f_i$ vanishes on all $m_i$ . Now, takes a function $f$ that only vanishes on $m ZZ$, where $m = lcm(m_1...m_n)+1$. If it's generated by $f_1,...,f_n$, then it is at least vanishing on $lcm(m_1,...,m_n) ZZ$ (since all $f_i$ vainishes on these points, due to $m_i$ dividing the given term), but based on this construction it's clearly not vanishing at $z = lcm(m_1,...,m_n)$, which causes a contradiction. (These mostly based on Complex Analysis, the construction of Weierstrass Function).

  Hence, $I$ cannot be finitely generated, showing that $cal(O)(CC)$ is not Noetherian in this sense.

4. If for fixed $k in NN$ we have first $k$ derivative of $f(z)$ vanishes at $0$, then the coefficients of $x,...,x^k$ must all be $0$, which it certainly forms a subring of $CC[z]$.
  
  Let $R subset.eq CC[z]$ denotes this ring, then we'll show that $R$ is in fact a Principal Ideal Domain: Integral Domain condition is satisfied as a subring of $CC[z]$. To prove that $I subset.eq R$ an ideal is principal, consider 
  

5. 

= ND//5
#myQuestion[
  Let $A$ be a Noetherian ring, $B$ a finitely generated $A$-algebra
]